
version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  test-serv:
    executor: 
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          command: npm test
          working_directory: ./server
          
  setup-docker:
     executor:
       name: node/default
     steps:
       - checkout
       - setup_remote_docker
       
  test-cli:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client
      - run:
          command: npm test
          working_directory: ./client

  publish-docker:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo \"$DOCKER_LOGIN\" | docker login -u \"dazaiii\" --password-stdin
            sudo docker build ./server -t dazaiii/srv
            sudo docker push dazaiii/srv
            
      - run:
          command: |
            echo \"$DOCKER_LOGIN\" | docker login -u \"dazaiii\" --password-stdin
            sudo docker build ./client -t dazaiii/cli
            sudo docker push dazaiii/cli


workflows:
    build-and-test:
      jobs:
        - docker-setup
        - test-serv:
          filters:
            branches:
             only:
               - master
        - test-cli:
          filters:
            branches:
             only:
               - master
        - publish-docker:
            filters:
              branches:
                only:
                  - master
            requires:
              - setup-docker
              - test-serv
              - test-cli
