version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor: 
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          command: npm test
          working_directory: ./server
#  building-server:
#     machine: true
#     steps:
#       - checkout
#       - run: | 
#           echo \"$DOCKER_PASS\" | docker login --username $DOCKER_USER --password-stdin
#       - run: docker build -t  dazaiii/ask2020-node-react-cicd ./server
#       - run: docker push dazaiii/ask2020-node-react-cicd
  building-server:
    machine: true
    steps:
      - checkout
      - run: |
          echo \"$DOCKER_PASS\" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t dazaiii/ask2020-node-react-cicd ./server .
      - run: docker push dazaiii/ask2020-node-react-cicd
workflows:
    build-and-test:
      jobs:
        - building server:
           filters:
             branches:
                only: master
        - build-and-test:
           filters:
             branches:
                only: master
