
version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  test-serv:
    executor: 
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          command: npm test
          working_directory: ./server
          
          
  setup-docker:
     executor:
       name: node/default
     steps:
       - checkout
       - setup_remote_docker
       
  test-cli:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client
      - run:
          command: npm test
          working_directory: ./client

  publish-docker:
    machine: true
    steps:
      - checkout
      - run:
          command: docker login -u dazaiii -p $DOCKER_LOGIN      
      - run:
          command: | 
            sudo docker build -t dazaiii/server ./server
            sudo docker push dazaiii/server
      - run:
          command: |
            sudo docker build -t dazaiii/client ./client
            sudo docker push dazaiii/client
         
workflows:
    build-and-test:
      jobs:
        - setup-docker
        - test-serv:
          filters:
            branches:
             only:
               - master
        - test-cli:
          filters:
            branches:
             only:
               - master
        - publish-docker:
            filters:
              branches:
                only:
                  - master
            requires:
              - setup-docker
              - test-serv
              - test-cli
