version: 2.1
orbs:
 node: circleci/node@2.1.0
jobs:
 build-and-test:
#  docker:
#   - image: circleci/node:latest
  working_directory: ./server/
  executor: 
   name: node/default
  steps:
   - checkout
#   - node/with-cache:
#    steps:
#     - run: npm install
#     - run: npm test
   - node/install-packages
#   - run: npm install
   - run: npm test
workflows:
 build-and-test:
  jobs:
   - build-and-test
#    filters:
#     branches:
#      ignore:
#      - dev
